controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\File;
use app\models\Homepage;
use app\models\Reference;
use app\models\Settings;
use Yii;
use yii\base\Application;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\ContactForm;
use yii\web\Response;

class SiteController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionIndex()
    {
        $mHomepage = new Homepage();
        $mSettings = Settings::getForAccount('senovo');

        $aArticles = $mHomepage->getArticles();
        $aCarousel = $mHomepage->getCarousel();
        $aReferences = $mHomepage->getReferences();

        $model = new ContactForm();

        /*if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }*/

        $this->view->params['contactForm'] = $model;

        return $this->render('index', [
            'mSettings' => $mSettings,
            'aArticles' => $aArticles,
            'aCarousel' => $aCarousel,
            'aReferences' => $aReferences
        ]);
    }

    /**
     * @param $offset
     * @param int $limit
     * @return string
     */
    public function actionReference($offset, $limit = 3)
    {
        $mReference = new Reference();

        $response = [
            'html' => ''
        ];

        $aReference = $mReference->search($offset, $limit);

        foreach ($aReference as $model) {
            $response['html'] .= $this->renderPartial('_reference', [
                'mReference' => $model
            ]);
        }

        $response['more'] = $mReference->hasMoreReferences ? 1 : 0;

        Yii::$app->response->format = Response::FORMAT_JSON;
        return $response;
    }

    /**
     * @param $hash
     */
    public function actionFile($hash)
    {
        /** @var File $mFile */
        $mFile = File::findOne(['hash' => $hash]);
        if ($mFile != null) {
            $file = $mFile->getAbsolutePath() . DIRECTORY_SEPARATOR . $mFile->path . DIRECTORY_SEPARATOR . $mFile->file_pk;

            header("Content-Description: File Transfer");
            header("Content-Type: application/octet-stream");
            header("Content-Disposition: attachment; filename=" . basename($mFile->name));

            readfile ($file);
            exit();
        }
    }

    /**
     * překopat !!! na ajax se ptát až při odpovědi...
     */
    public function actionSubmit()
    {
        $request = Yii::$app->request;
        if (!$request->getIsAjax()) {
            //Yii::$app->session->setFlash('warning')

            return $this->redirect(['/site/index']);
        }  else {
            $response = [];

            if (!$request->getIsPost()) {
                $response['error'] = "Neplatný požadavek!";
            } else {

                $post = $request->post();

                var_dump($post); die;

                $mForm = new ContactForm();
                $recipients = [
                    ['lukas.senohrabek@email.cz' => 'Lukáš Senohrábek']
                ];

                if ($mForm->load($post) && $mForm->contact($recipients)) {
                    $response['success'] = 1;
                } else {
                    //$errors = $mForm->getFirstErrors();
                    $response['error'] = "Chyba při odesílání emailu, opakujte akci později.";
                }
            }

            Yii::$app->response->format = Response::FORMAT_JSON;
            return $response;
        }
    }
}

views/site/_article.php
<?php
/**
 * Created by PhpStorm.
 * User: Senik
 * Date: 03.01.2016
 * Time: 21:47
 *
 * @var Article $mArticle
 */

use app\models\article\Article;
use yii\bootstrap\Html;
?>

<article class="bg1" id="<?= $mArticle->article_id ?>">
    <div class="row">
        <div class="article-content">
            <div class="arrow"></div>
            <div class="article-text">
                <div class="heading-buttons">
                    <h3><?= $mArticle->title ?></h3>
                    <?php
                    if ($mArticle->show_up) {
                        echo Html::a('Nahoru ' . Html::icon('arrow-up'), '#', ['data-scroll' => 'top']);
                    }
                    ?>
                    <div class="clearfix"></div>
                </div>

                <?= $mArticle->content ?>
            </div>
        </div>
        <div class="article-image"></div>
    </div>
    <div class="spacer"></div>
</article>

views/site/_contact.php
<?php
/**
 * @var ContactForm $model
 */

use app\models\ContactForm;
use yii\bootstrap\ActiveForm;

$form = ActiveForm::begin([
    'id' => 'contact-form',
    'action' => ['/site/submit'],
    'method' => 'POST'
]);
?>

    <div class="row">
        <div class="col-md-6">
            <?= $form->field($model, 'name')->textInput([/*'placeholder' => $model->getAttributeLabel('name')*/]) ?>
        </div>
        <div class="col-md-6">
            <?= $form->field($model, 'email')->textInput([/*'placeholder' => $model->getAttributeLabel('email')*/]) ?>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <?= $form->field($model, 'body')->textarea([/*'placeholder' => $model->getAttributeLabel('body')*/]) ?>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="g-recaptcha" data-sitekey="<?= Yii::$app->params['recaptcha']['site-key'] ?>"></div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="pull-right">
                <?= \yii\bootstrap\Html::submitButton('Odeslat', ['class' => 'btn btn-primary']) ?>
            </div>
        </div>
    </div>

<?php
ActiveForm::end();

views/site/_reference.php
<?php
/**
 * Created by PhpStorm.
 * User: Senik
 * Date: 03.01.2016
 * Time: 21:47
 *
 * @var Reference $mReference
 */

use app\assets\FancyBoxAsset;
use app\models\File;
use app\models\reference\Reference;
use yii\bootstrap\Html;

FancyBoxAsset::register($this);
?>

<div class="row reference">
    <div class="col-md-12">
        <div class="reference-image">
            <!-- otaceni obrazku - https://davidwalsh.name/css-flip -->
            <img src="<?= $mReference->getType()->getIconFullPath() ?>">
        </div>
        <div class="reference-content">
            <p>
                <b><?= Yii::$app->formatter->asDate($mReference->ref_date) ?></b>
            </p>
            <?= $mReference->content ?>

            <?php
            if ($mReference->link != null) {
                echo Html::tag('p', Html::a($mReference->link, $mReference->link, ['target' => '_blank']));
            }
            ?>

            <div class="row">
                <div class="col-md-12 reference-gallery-wrapper">
                    <?php if ($mReference->hasGallery()): ?>
                        <?php /** @var \app\models\photo\Photo $photo */ ?>
                        <?php foreach ($mReference->gallery->photos as $photo): ?>
                            <?php
                            $thumb = $photo->thumbnail;
                            $file = $photo->getFirstLargestFile();

                            echo Html::a(
                                Html::img(['/site/file', 'hash' => $thumb->hash], ['class' => 'img-thumbnail']),
                                ['/site/file', 'hash' => $file->hash],
                                ['data-fancybox' => $mReference->gallery->photogallery_id, 'rel' => $mReference->gallery->photogallery_id]
                            );
                            ?>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>
</div>

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php

/**
 * @var $this yii\web\View
 * @var $mSettings Settings
 * @var $aArticles Article[]
 * @var $aCarousel array
 * @var $aReferences Reference[]
 */

use app\models\article\Article;
use app\models\Reference;
use app\models\Settings;
use yii\bootstrap\Html;

$this->title = 'Senovo.cz | PC sestavy, HW & SW & Sítě, Programování, weby a infromační systémy';
?>

<div class="site-index">
    <div class="body-carousel">
        <div class="container">
            <div class="macbook">
                <?= \yii\bootstrap\Carousel::widget([
                    'id' => 'carousel-hp',
                    'items' => $aCarousel,
                ]) ?>
            </div>
        </div>
    </div>

    <div class="body-content">
        <?php
        foreach ($aArticles as $mArticle) {
//            echo $this->render('_article', [
//                'mArticle' => $mArticle
//            ]);
            echo \app\components\widgets\article\ArticleWidget::widget(['model' => $mArticle]);
        }
        ?>
    </div>

    <div class="body-reference" id="reference">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="heading-buttons">
                        <h2>Reference</h2>
                        <?php
                        echo Html::a('Nahoru ' . Html::icon('arrow-up'), '#', ['data-scroll' => 'top'])
                        ?>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>

            <div id="reference-wrapper">
            <?php
            $keys = array_keys($aReferences);

            for ($i = 0; $i < $mSettings->getInitialReferencesCount(); $i++) {
                $reference_pk = $keys[$i];

                echo $this->render('_reference', [
                    'mReference' => $aReferences[$reference_pk]
                ]);
            }

            if (count($aReferences) > $mSettings->getInitialReferencesCount()) {
            ?>
            </div>

            <div class="row">
                <div class="col-md-12 text-center">
                    <?= Html::button('Zobrazit více', ['class' => 'btn btn-info', 'id' => 'more-references']) ?>
                </div>
            </div>
            <?php
            }
            ?>
        </div>
    </div>
</div>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'options' => ['class' => 'form-horizontal'],
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'username') ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

    <div class="col-lg-offset-1" style="color:#999;">
        You may login with <strong>admin/admin</strong> or <strong>demo/demo</strong>.<br>
        To modify the username/password, please check out the code <code>app\models\User::$users</code>.
    </div>
</div>